<Project>
  <PropertyGroup>
    <Version>2.2.1</Version>
    <PackageVersion>2.2.1</PackageVersion>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
    
    <Authors>Tatyana Asriyan</Authors>
    <Company>Treiben</Company>
    
    <PackageProjectUrl>https://github.com/Treiben</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Treiben/Propel.FeatureFlags</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>feature-flags;dotnet;release;user-targeting;percentage-rollout;a/b-testing;multi-tenant;tenant-targeting;on-off-toggle;type-safe;postgres;sql-server;redis</PackageTags>
    <IsPackable>false</IsPackable>
    <PackageIcon>propel.png</PackageIcon>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)/README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)propel.png" Pack="true" PackagePath="propel.png" />
  </ItemGroup>
</Project>